apiVersion: apps/v1
kind: Deployment
metadata:
  name: resale-dev-customer-front-app
  namespace: dev-resale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resale-dev-customer-front-app
  template:
    metadata:
      labels:
        app: resale-dev-customer-front-app
    spec:
      imagePullSecrets:
          - name: icr-secret
      containers:
        - name: resale-dev-customer-front-app
          image: de.icr.io/dev-registry/loveresale-customer-frontend:latest
          imagePullPolicy: Always
          # env:
          #   - name: BANK_URL
          #     valueFrom:
          #       configMapKeyRef:
          #         name: backend-properties
          #         key: BANK_URL
          #   - name: CHATBOT_ID
          #     valueFrom:
          #       configMapKeyRef:
          #         name: backend-properties
          #         key: CHATBOT_ID
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 1000Mi
              cpu: 250m
            requests:
              memory: 200Mi
              cpu: 125m
      dnsPolicy: Default

---
apiVersion: v1
kind: Service
metadata:
  name: resale-dev-customer-front-service-cip
  namespace: dev-resale
  labels:
    app: resale-dev-customer-front-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: resale-dev-customer-front-app
